export const TypeReducer = {
    "INITIALIZE": "INITIALIZE",
    "INITIALIZE_SERIE": "INITIALIZE_SERIE",
    "INITIALIZE_ROMANCE": "INITIALIZE_ROMANCE",
    "INITIALIZE_ANIMATION": "INITIALIZE_ANIMATION",
    "INITIALIZE_COMEDY": "INITIALIZE_COMEDY",
    "INITIALIZE_FAMILY": "INITIALIZE_FAMILY",
    "INITIALIZE_HORROR": "INITIALIZE_HORROR",
    "INITIALIZE_SCIENCE_FICTION": "INITIALIZE_SCIENCE_FICTION",
    "INITIALIZE_TRILLER": "INITIALIZE_TRILLER",
    "HISTORY": "HISTORY",
    "INITIALIZE_DOCUMENTARY": "INITIALIZE_DOCUMENTARY",

}


